### ISSUE TITLE
Compilation hint: 'dump' cannot raise 'YamlSerializationError' [XCannotRaiseY]

### ISSUE THREAD

**Issue by jfilby** [flyx/NimYAML#111]
I have a compilation hint when calling dump():

```
.nimble\pkgs\yaml-0.16.0\yaml\serialization.nim(1432, 23) Hint: 'dump' cannot raise 'YamlSerializationError' [XCannotRaiseY]
```

The code is on GitHub: https://github.com/jfilby/nexus/blob/main/src/nexus/cmd/service/generate/tmp_dict/tmp_dict_utils.nim
Function: writeTmpDict()

**Comment by jfilby** [comment]
OK, but perhaps it can be hidden with a -d compiler switch? When I scan for warnings it would be useful to ignore this.

**Comment by flyx** [comment]
Hm, I think this can be solved with

```nim
{.push: hint[XCannotRaiseY]: off.}
…
{.pop.}
```

around the relevant declarations. Don't have the time to test this right now but I'll do that soon-ish.

**Comment by flyx** [comment]
So… that doesn't work. As explained in [this thread](https://forum.nim-lang.org/t/6954), due to lazy compilation, the push/pop pragmas must be around the code that causes the `dump` function to compile, which is, due to lazy compilation, the calling code. I imagine you don't want to put that around every call to `dump` on your side.

Testing also showed that yours is not the only hint that may potentially be shown, another one is

    NimYAML/yaml/serialization.nim:400:44 Hint: 'representObject' cannot raise 'ValueError'

*Something* should certainly be done about these. My Nim is a bit rusty (not doing anything in Nim but maintaining this lib) but I'd imagine doing something like

```nim
when defined(doNimYamlTest):
  {.push raises: […].}

# … code …

when defined(doNimYamlTest):
  {.pop.}
```

might work. This would remove the explicit annotations in production while still being able to check their validity during testing. The only question remaining would be how to treat this on the API docs (should they still show the annotation or not?).

This would need a larger refactoring to group all similarly annotated procs together (or put the stuff about around every single one). In case you know a more elegant solution, I'd love to hear it.

**Comment by jfilby** [comment]
It seems hints can be silenced with pragmas:

```
  {.hint[XCannotRaiseY]: off.}
```
