### ISSUE TITLE
ignore pragma doesn't work on nested maps

### ISSUE THREAD

**Issue by daylinmorgan** [flyx/NimYAML#127]
When using the `{.ignore: [].}` pragma to ignore all unknown fields an error is raised if the value is a map. 
```nim
import yaml

type
  IgnoreMap {.ignore: [].} = object
    warbl: int

  IgnoreNamedMap {.ignore: ["rtuco"].} = object
    warbl: int

let nestedInput = """
rtuco:
  foo: bar
warbl: 1
"""

proc attemptLoad[T](s:string, x:typedesc[T], pragma:string) =
  var result: T
  try: 
    load(s, result)
  except YamlConstructionError as e:
    echo "failed to load with " & pragma
    echo "error:" & e.msg

attemptLoad(nestedInput,IgnoreMap,"ignore: []")
attemptLoad(nestedInput,IgnoreNamedMap,"ignore:[\"rtuco\"]")

```

The above fails with `IgnoreMap` and raises:
```bash
failed to load with ignore: []
error:Expected field name, got yamlStartMap
```

If this is intentional is there a way to specify that nested data should be ignored on an object without knowing the field name?

**Comment by flyx** [comment]
Certainly not intentional, this is an error.

Error is here: 

https://github.com/flyx/NimYAML/blob/7dd8e88639b86f43d0a76f7c3763234c68741026/yaml/serialization.nim#L816-L821


This portion of the macro creates the branch that is executed when a field name is not mappable. The generated AST looks like this:

```nim
when failOnError:
  raise constructionError(…)
```

when `ignore` has been set and is empty, this branch is reached with `failOnError` being **`false`**, so… nothing happens. This is bad.

Compare what happens when there are explicitly ignored field names and a field is encountered with one of those names: 

https://github.com/flyx/NimYAML/blob/7dd8e88639b86f43d0a76f7c3763234c68741026/yaml/serialization.nim#L892-L899

The fix would be:

 * extract the code skipping over the value to an own function
 * generate an **`else`** branch for the **`when`** statement above and call this function

My Nim is a bit rusty so if you want to tackle this a PR would be very welcome :)
