### ISSUE TITLE
Please, call the package nimyaml

### ISSUE THREAD

**Issue by andreaferretti** [flyx/NimYAML#16]
The package name should be `nimyaml`, as is the registered name in the Nimble package list.

This amounts to changing the `yaml.nimble` to `nimyaml.nimble` (no changes required in the actual code - it can still be imported with `import yaml`).

Otherwise, depending on `nimyaml` in a different nimble project causes issues. Namely, Nimble will install `nimyaml` as a dependency, but will use a folder like `yaml-0.6.0`. Next time nimble is run, it will **not** detect nimyaml as installed, due to the name mismatch, and will try to clone it again. But the directory exists, hence it will ask for confirmation (defaulting to no overwrite). In case the user does not confirm, nimble exits immediately.

This make nimyaml very inconvenient to use as a dependency in another project

**Comment by flyx** [comment]
The package was originally called `nimyaml` because there already was a package called `yaml`. As this package is no longer being actively developed, I talked with dom96 and the package's author (see [here](https://github.com/nim-appkit/yaml/issues/1)) and we decided to drop the old `yaml` package and rename `nimyaml` to `yaml`.

`nimyaml` is still a nimble package, but its use is deprecated, because nimble will some time in the future enforce that package name == import name. That was also a reason for the renaming.

So just update your project's dependency from `nimyaml` to `yaml` and the issue will go away. Using `nimyaml` will cease to work once the nimble rule is enforced.
