### ISSUE TITLE
Wrong line in error reporting

### ISSUE THREAD

**Issue by andreaferretti** [flyx/NimYAML#23]
When there is a parsing error at the end of a line, the corresponding exception has the wrong line number (1 more than the correct number).

For instance, parsing a file such as

```yaml
name: Andrea
age: abc
surname: Ferretti
```

with the following code

```nim
import yaml

type Person = object
  name, surname: string
  age: int

var
  s = newFileStream("test.yaml", fmRead)
  c: Person
try:
  load(s, c)
except YamlConstructionError:
  let e = (ref YamlConstructionError)(getCurrentException())
  echo "ERROR at line ", e.line, " column ", e.column
  echo e.lineContent
  echo e.msg
finally:
  s.close()
```

will print

```
ERROR at line 3 column 6
surname: Ferretti
     ^

Cannot construct to int32: abc
```

This seems not to happen when the error is, say, finding a field when a sequence was expected.

I am not sure where this exactly comes from, because I see the lexer state comes from `lexbase`, but I will let you know if I find anything.

I hope I am not bothering you too much! :-)

**Comment by flyx** [comment]
It's a good thing you use the lib, so that these errors surface. Keep reporting!

**Comment by flyx** [comment]
There is no easy solution for this. After `abc`, the parser starts reading the next line because it may be a multiline scalar. Upon encountering `surname` at the uppermost indentation level, it determines that the scalar does not continue here and yields the token `abc`. However, the lexer has already entered the next line and therefore, when the serialization queries the current line to report the error, it gets the line after `abc`. By design, BaseLexer may have already dumped the previous line.

Two possibilities to solve this:

 * Cache the starting line in the parser and preserve it until the token is finalized. This gravely cripples performance and is therefore not a viable solution.
 * Remove the `lineContent` field from the exception because it does not work properly. Instead, provide a utility proc, that, provided with the exception and the whole YAML source as Stream, renders the line with marker. This may not be optimal because it does not cover all use-cases (e.g. if you process YAML directly from an non-resettable data stream), but is probably the cleanest solution.

**Comment by flyx** [comment]
This is now fixed as follows:

 * if the parser is invoked with a `Stream` as source (like in the code given here),
   * if the lexer is still in the same line, it returns the line with marker.
   * if the lexer has already advanced to the next line, it returns the empty string.
 * If the parser is invoked with a `string` as source (new API), the line will always be correctly displayed.

Example:

```nim
import yaml

type Person = object
  name, surname: string
  age: int

var
  s = """name: Andrea
age: abc
surname: Ferretti"""
  c: Person
try:
  load(s, c)
except YamlConstructionError:
  let e = (ref YamlConstructionError)(getCurrentException())
  echo "ERROR at line ", e.line, " column ", e.column
  echo e.lineContent
  echo e.msg
```

will display:

```
ERROR at line 2 column 6
age: abc
     ^

Cannot construct to int32: abc
```

**Comment by andreaferretti** [comment]
Great, thank you very much!
