### ISSUE TITLE
Support strict JSON loading.

### ISSUE THREAD

**Issue by Varriount** [flyx/NimYAML#38]
Being able to load JSON (and not YAML, which is a superset) would be a nice feature. I know that NimYAML is meant to primarily be a YAML loader, so perhaps this would be better as a separate project.

**Comment by flyx** [comment]
What would be the benefit of having a dedicated JSON loader? The existing loader is able to load any JSON. I can think of some benefits, but none of them really justify the complexity it adds:

 * Identifying invalid JSON that would be valid YAML (but I am unsure in which scenario NimYAML is the right tool for this)
 * Faster loading (parsing JSON is significantly faster than parsing YAML, though lesser than a magnitude). I once or twice heard about people parsing multiple MBs of data, but that seems to be a rather exotic use-case. For small amounts of data, the performance increase should not be that relevant.
 * Motivating people to use NimYaml instead of `marshal` to (de)serialize JSON. That would be a marketing reason, which, in my eyes, is not really a *good* reason.

**Comment by flyx** [comment]
For the record, I thought about de-coupling NimYAML's serialization API from the YAML backend so it can be used with different backends (XML, INI, you name it). But unfortunately, this would mean to change the intermediate representation (currently the `YamlStream`) to accommodate the very different structure of XML, for example. I have not yet succeeded in crafting such a representation that fits all needs, so I currently go with YAML-only.

**Comment by Varriount** [comment]
My use-case is primarily #1. There are some services out there which consume files written in JSON in order to perform actions, and I sometimes have to write scripts which augment existing files created for these services.

**Comment by flyx** [comment]
For augmenting an existing JSON file, doesn't it suffice to load it as YAML and dump it with `psJson`? Your use-case doesn't sound like you would need to ensure that the original file is valid JSON. The augmented file will be.

**Comment by flyx** [comment]
Closing this since it is out-of-scope for NimYAML.
