### ISSUE TITLE
Using load() on a JSON parses `null` as string "null" instead of `nil`

### ISSUE THREAD

**Issue by davidnorthetal** [flyx/NimYAML#44]
Using **dump** with the psJson style writes out an empty string "" as **null**, however when then loading it back via a plain **load** it parses it back as string "null", effecitvely turning all empty strings into "null" strings.

**Comment by flyx** [comment]
**load** behaves correctly by loading the scalar `null` into the string `"null"`. This is because the tag resolution for such scalars is defined as application-specific in the YAML specification. NimYAML loads `null` as nil value for **ref** types, but not for value types such as **string**. I designed it that way because a `nil` string in Nim is rather rare and may be unexpected by the user. NimYAML only loads a nil string if you exlicitly use the tag `!n!nil:string` in the YAML input.

That being said, the presenter is at fault here for presenting an empty string as `null`. This is a bug and I have to fix it.
