### ISSUE TITLE
Join to NimParsers organization

### ISSUE THREAD

**Issue by data-man** [flyx/NimYAML#57]
You are welcome!

It will be convenient to have any parsers under one "roof".

**Comment by flyx** [comment]
I am unsure about the benefits. Organizations are for projects that are developed by a group of people and/or to manage projects that are tightly integrated. I wouldn't use them as a directory for related projects, since that grouping is better done with tagging inside the nimble package list. Example: Imagine someone creates an organization for Nim serialization tools. NimYAML would certainly also fit in there, but can only be part of one organization. However, in the nimble package list, it can have any number of tags, which makes that the better mechanism.
