### ISSUE TITLE
yaml.set_default_value with ref object

### ISSUE THREAD

**Issue by absolutejam** [flyx/NimYAML#66]
Hi,

First off, props on this awesome project! Nice to see such a polished, well-documented project as part of the Nim ecosystem :+1: 

Just a query really - I'm trying use `yaml.set_default_value` on a ref object, and it's not compiling. I'm not sure if this is a limitation of this macro or if there's a way I need to kinda deref the ref object(?).

My example is:
```
type Config = ref object
    docs_root*: string
    drafts_root*: string

yaml_set_default_value(Config, docs_root, "~/.example")

# Error
stack trace: (most recent call last)
../../../.nimble/pkgs/yaml-0.11.0/yaml/serialization.nim(1453, 13) getFieldIndex
../../../.choosenim/toolchains/nim-#devel/lib/core/macros.nim(1196, 11) $
../../../.choosenim/toolchains/nim-#devel/lib/system.nim(3978, 20) failedAssertImpl
../../../.choosenim/toolchains/nim-#devel/lib/system.nim(3971, 11) raiseAssert
../../../.choosenim/toolchains/nim-#devel/lib/system.nim(3011, 7) sysFatal
notorious.nim(26, 23) template/generic instantiation of `setDefaultValue` from here
../../../.nimble/pkgs/yaml-0.11.0/yaml/serialization.nim(1561, 69) template/generic instantiation of `getFieldIndex` from here
../../../.choosenim/toolchains/nim-#devel/lib/system.nim(3011, 7) Error: unhandled exception: /home/james/.choosenim/toolchains/nim-#devel/lib/core/macros.nim(1196, 17) `false` Invalid node kind nnkBracketExpr for macros.`$`
```

Any idea if this is doable?

Regards.

EDIT: Forgive the snake_case!

**Comment by flyx** [comment]
Looking at the `tserialization.nim` testsuite, I never really tested with `ref` objects, so it could well be that this is the problem. If that's the case, you should be able to fix it with this:

    type
      ConfigObj = object
        docs_root*: string
        drafts_root*: string
      Config = ref ConfigObj

    yaml.set_default_value(ConfigObj, docs_root, "~/.example")

The stacktrace points to [this line](https://github.com/flyx/NimYAML/blob/devel/yaml/serialization.nim#L1453), and the error message tells me that for some reason, `$tDesc[1]` fails to compile because the `$` function cannot work on a bracketed expression for some reason. That  hints to a problem with the compiler rather than a `ref` incompatibility.

Changes to the Nim compiler have broken NimYAML multiple times in the past, because NimYAML quite heavily depends on compile-time ASTs and macros and those have been less stable than the other parts of the language. It may well be that `setDefaultValue` currently does not work at all because of some change.

PS: I am not actively using Nim currently, so I don't have a Nim environment available to do some testing. I mainly give advice and accept PRs here ;).

**Comment by flyx** [comment]
#82 has information about how this works now, documentation will be updated – hopefully soon :).
