### ISSUE TITLE
ObjectType: Missing field for Option

### ISSUE THREAD

**Issue by hugosenari** [flyx/NimYAML#82]
## Current Behavior
When you try to load some yml without some Option field it raises 

`ObjectType: Missing field: "fieldName" [YamlConstructionError]`

## Expected Behavior
Since field type is Option[T], I would expect it ignore this and use none(T) instead of throwing exception.

## Context (Environment)
yml:
```yml
name: bla
```
nim:
```nim
type MyType = ref object of RootObj
   name*: Option[string]
   description*: Option[string]
```

**Comment by flyx** [comment]
This is not how NimYAML is handling `Option` fields. Instead, it requires to be given a value, but that value may be `!!null` in which case the field is set to `none[T]`.

You can achieve your desired behavior by doing

```nim
type MyType = ref object of RootObj
   name*: Option[string]
   description*: Option[string]
setDefaultValue(MyType, name, none[string])
setDefaultValue(MyType, description, none[string])
```

The justification is that this is more flexible. If `Option` fields would be automatically processed like this, you couldn't specify that you *want* to require the field in the YAML even if it holds the value `!!null`.

The actual issue is that the handling of `Option` is not described in the documentation. I will close this once I added it there.

**Comment by hugosenari** [comment]
setDefaultValue throws: Error: Invalid node kind nnkBracketExpr for macros.\`$\` :unamused: 

```
/yaml-0.13.1/yaml/serialization.nim(1506, 13) getFieldIndex
/nim/core/macros.nim(1279, 5) $
ymlcli.nim(27, 16) template/generic instantiation of `setDefaultValue` from here
/yaml-0.13.1/yaml/serialization.nim(1614, 69) template/generic instantiation of `getFieldIndex`
/yaml-0.13.1/yaml/serialization.nim(1505, 20) Error: Invalid node kind nnkBracketExpr for macros.`$`
```

**Comment by hugosenari** [comment]
Also, almost all my fields are Option[T], this means that I should set one by one as none(T)?

Before a forgot again: thank you for all your help and attention :smiley:

**Comment by flyx** [comment]
Hmm, seems like you hit #66 . I hoped it went away with a compiler update. I'll look into that. Depending on how that issue can be resolved, it may be possible to provide a macro to tell NimYAML to treat all `Option` fields to as having `none(T)` as default value.

**Comment by flyx** [comment]
I looked into the code a bit. `setDefaultValue` simply does not support `ref` types at all, and the fix is not trivial. Probably the easiest way to fix this is to replace `setDefaultValue` with a [custom annotation](https://nim-lang.org/docs/manual.html#userminusdefined-pragmas-custom-annotations) which would be nicer anyway. Frankly, the whole `setDefaultValue` code is a horrible mess and it does unspeakable things with the AST. Either custom annotations did not exist when I wrote that or I was blatantly ignorant about it.

I can't promise anything but I will try to fix this.

**Comment by flyx** [comment]
Okay so I pushed a fix to devel. It works like this now:

```yaml
import yaml
import options

type MyType = ref object of RootObj
   name* {.defaultVal: none(string).}: Option[string]
   description* {.defaultVal: none(string).}: Option[string]

let input = "{}"
var v: MyType
load(input, v)
echo v.name
echo v.description
```

Currently this works per field. I think providing a macro to do it for the whole type would be nice, e.g.

```yaml

type MyType {.optionalOptions.} = ref object of RootObj
   name*: Option[string]
   description*: Option[string]
```

I dislike the idea of having a global pragma for this since it might affect code in other compilation units.

**Comment by flyx** [comment]
There now is `{.sparse.}` which will make all `Option` fields of a type optional. I just pushed a new version `0.14.0` containing the annotations and [the docs](https://nimyaml.org/yaml.annotations.html) to the website.
